name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[agentic] ruff black pytest coverage pyinstaller
      - name: Ruff
        run: ruff .
      - name: Black
        run: black --check .
      - name: Pytest
        run: pytest --cov=smart_price --cov=tests --cov-report=term-missing
  build-exe:
    runs-on: windows-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[agentic] pyinstaller
      - name: Build
        run: ./build_windows_exe.bat
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart_price_exe
          path: dist/*.exe
